theme: jekyll-theme-minimal

github:
  is_project_page: false

# Google Analytics
google_analytics: UA-65900970-2

logo: assets/logo.png

comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"